name: qernal-ci

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # validate commits
  commit:
    if: '! github.event.pull_request.draft'
    uses: ./.github/workflows/conventional-commits.yaml
    with:
      lint_only: true